# Site settings
title: Statistical Innovators in Medical Product Development Committee
# description: Empowering Statistical Innovation in Pharmaceuticals
baseurl: ""
url: "https://statisticalinnovation.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages
repository: statisticalinnovation/statisticalinnovation.github.io
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - orgnization.md
  - summit-2025.md
  - summit-2024.md
  - summit-2023.md
  - resources.md

# Author info
author:
  name: Statistical Innovation Community
  email: statinnovation@gmail.com

# Social
twitter_username: statisticalinnovation
github_username: statisticalinnovation

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
